name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    # - name: Build the Docker image
    #   run: docker build . --file faiss-base.dockerfile --tag my-image-name:$(date +%s)
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: faiss-base.dockerfile
        push: true # Will only build if this is not here
        tags: |
          farhannz/faiss-base:latest
